export enum NotificationType {
  EXAM_RESULT_AVAILABLE = "EXAM_RESULT_AVAILABLE",
  ASSIGNMENT_SUBMITTED = "ASSIGNMENT_SUBMITTED",
  ASSIGNMENT_GRADED = "ASSIGNMENT_GRADED",
  STUDENT_ENROLLED = "STUDENT_ENROLLED",
  STUDENT_IMPORT_COMPLETE = "STUDENT_IMPORT_COMPLETE",
  STUDENT_IMPORT_FAILED = "STUDENT_IMPORT_FAILED",
  TENANT_REGISTERED = "TENANT_REGISTERED",
  CREDENTIAL_FAILED = "CREDENTIAL_FAILED",
  SYSTEM_ERROR = "SYSTEM_ERROR",
  ANNOUNCEMENT = "ANNOUNCEMENT",
}

export type NotificationTab = "unread" | "read";
