"use client";
import {useEffect,useState,type FormEvent} from "react";
import {Filter,RotateCcw} from "lucide-react";
import type {AuditQuery} from "@/modules/audit/domain/builder/AuditQueryBuilder";
import TextField from "@/shared-ui/component/TextField";
import SelectField from "@/shared-ui/component/SelectField";
import Button from "@/shared-ui/component/Button";
export function AuditFilterBar({query,isAdmin,onApply,onReset}:{query:AuditQuery;isAdmin:boolean;onApply:(q:AuditQuery)=>void;onReset:()=>void}){
 const [draft,setDraft]=useState(query);const [advanced,setAdvanced]=useState(false);useEffect(()=>setDraft(query),[query]);
 const set=(key:keyof AuditQuery,value:string)=>setDraft(prev=>({...prev,[key]:value.trim()||undefined}));
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();onApply({...draft,page:1,tenantId:isAdmin?draft.tenantId:undefined})};
 return <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-[minmax(0,2fr)_repeat(2,minmax(0,1fr))_auto]"><TextField label="Cari pengguna, aksi, resource..." value={draft.search??""} onChange={e=>set("search",e.target.value)} maxLength={150}/><SelectField label="Semua Role" value={draft.actorRole??""} onChange={e=>set("actorRole",e.target.value)}><option value="">Semua Role</option>{["ADMIN","TENANT","PROCTOR","TEACHER","STUDENT","SYSTEM"].map(role=><option key={role} value={role}>{role}</option>)}</SelectField><SelectField label="Urutkan" value={draft.sortOrder} onChange={e=>set("sortOrder",e.target.value)}><option value="desc">Terbaru</option><option value="asc">Terlama</option></SelectField><Button type="submit" leftIcon={Filter} className="min-h-11 self-end">Filter</Button></div><div className="mt-3 flex items-center justify-between gap-2"><Button variant="text" color="secondary" onClick={()=>setAdvanced(value=>!value)}>{advanced?"Sembunyikan filter lanjut":"Filter lanjutan"}</Button><Button variant="outline" color="secondary" leftIcon={RotateCcw} onClick={onReset}>Reset</Button></div>{advanced&&<div className="mt-4 grid gap-4 border-t border-slate-100 pt-4 sm:grid-cols-2 xl:grid-cols-4"><TextField label="Dari (WIB)" type="date" value={draft.from??""} onChange={e=>set("from",e.target.value)}/><TextField label="Sampai (WIB)" type="date" value={draft.to??""} onChange={e=>set("to",e.target.value)}/><TextField label="Aksi" value={draft.action??""} onChange={e=>set("action",e.target.value)}/><TextField label="Resource" value={draft.resource??""} onChange={e=>set("resource",e.target.value)}/>{isAdmin&&<TextField label="Tenant ID" value={draft.tenantId??""} onChange={e=>set("tenantId",e.target.value)}/>}</div>}</form>
}
